# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: mysql-migration-script
#   annotations:
#   # This is what defines this resource as a hook. Without this line, the
#   # job is considered part of the release.
#     "helm.sh/hook": pre-install
#     "helm.sh/hook-weight": "-5"
#     "helm.sh/hook-delete-policy": hook-succeeded
# data:
#   init.sql: |
#     CREATE DATABASE IF NOT EXISTS mydb;
#     USE mydb;
#     CREATE TABLE IF NOT EXISTS users (
#       id INT PRIMARY KEY AUTO_INCREMENT,
#       name VARCHAR(100),
#       email VARCHAR(100)
#     );
